//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.Summary {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Summary.ICurrencyResultSummaries", CallbackContract=typeof(WcfClient.Summary.ICurrencyResultSummariesCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICurrencyResultSummaries {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICurrencyResultSummaries/GetResultSummaries")]
        void GetResultSummaries(int summariesAmount);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICurrencyResultSummaries/GetResultSummaries")]
        System.Threading.Tasks.Task GetResultSummariesAsync(int summariesAmount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyResultSummariesCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICurrencyResultSummaries/GetResultSummariesResult")]
        void GetResultSummariesResult(WcfCallbackServiceContract.APIConnection.ResultSummary[] summaries);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyResultSummariesChannel : WcfClient.Summary.ICurrencyResultSummaries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyResultSummariesClient : System.ServiceModel.DuplexClientBase<WcfClient.Summary.ICurrencyResultSummaries>, WcfClient.Summary.ICurrencyResultSummaries {
        
        public CurrencyResultSummariesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CurrencyResultSummariesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CurrencyResultSummariesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyResultSummariesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyResultSummariesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetResultSummaries(int summariesAmount) {
            base.Channel.GetResultSummaries(summariesAmount);
        }
        
        public System.Threading.Tasks.Task GetResultSummariesAsync(int summariesAmount) {
            return base.Channel.GetResultSummariesAsync(summariesAmount);
        }
    }
}
